name: springroll
services:
  db:
    image: postgres:15-alpine
    container_name: springroll_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: springroll_db
      POSTGRES_USER: postgres
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d springroll_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net


  backend:
    build:
      context: ./backend
    container_name: springroll_backend
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 8000
      ALLOW_DYNAMIC_CORS: 'true'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net
    cap_drop:
      - ALL

  frontend:
    build:
      context: ./frontend
    container_name: springroll_frontend
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - frontend-net
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
    internal: true

volumes:
  pgdata:
